### PR TITLE
Open mandatory studies in iframe inside modal

### PR DESCRIPTION
**Pull request by nathanstitt**
image

### CODE REVIEW

**Comment by reedstrm** [comment]
So, only mandatory studies are presented as modals? Seems reasonable, especially for this "on boarding deomgraphics" one.

**Review by reedstrm — APPROVED** [review]

**Comment by nathanstitt** [comment]
yes, @ck47-openstax said that only mandatory should open in modal, the rest should full-screen

**Comment by reedstrm** [comment]
@ck47-openstax  Take a peek, this look like what you intended?

**Comment by ck47-openstax** [comment]
@reedstrm @nathanstitt yesssss, excellent! 👌

**Pull request merged**
